name: Android CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Android App
    runs-on: ubuntu-latest

    env:
      MYAPP_RELEASE_STORE_FILE: release.keystore
      MYAPP_RELEASE_KEY_ALIAS: ${{ secrets.MYAPP_RELEASE_KEY_ALIAS }}
      MYAPP_RELEASE_KEY_PASSWORD: ${{ secrets.MYAPP_RELEASE_KEY_PASSWORD }}
      MYAPP_RELEASE_STORE_PASSWORD: ${{ secrets.MYAPP_RELEASE_STORE_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm install

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          sdk-platforms: 'android-35'
          ndk-version: '27.1.12297006'

      - name: Decode Keystore from GitHub Secrets
        run: |
          echo "${{ secrets.MYAPP_RELEASE_STORE_BASE64 }}" | base64 --decode > android/app/release-keystore

      - name: Grant execute permission to Gradle
        run: chmod +x ./android/gradlew

      - name: Build Release APK
        working-directory: android
        run: ./gradlew assembleRelease

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: android/app/build/outputs/apk/release/app-release.apk
